---
- hosts: linux_hosts
  become: true
  tasks:
  - name: Install OpenJDK 11
  apt:
  name: openjdk-11-jdk
  state: latest
  update_cache: yes

## esto es para tener el contenido a mano de los archivos, siempre hay que tomar en cuenta la indentacion